### ISSUE TITLE
Step-by-step instructions to get examples up and running

### ISSUE THREAD

**Issue by robot-army** [sdu-cfei/modest-py#78] opened 2021-10-12 18:44 UTC
Hi, 

I'm having some difficulty getting the example code up and running. I cloned the github repo on a new Ubuntu linux VM and ran pip install . 

I then ran `python3 ./examples/simple/simple.py`

The output looks like:
 ```Failed to load shared library /tmp/tmpfu8_31x3/binaries/linux64/Simple2R1C.so. libgfortran.so.3: cannot open shared object file: No such file or directory
[Errno 2] No such file or directory: 'examples/simple/resources/Simple2R1C_ic_linux64.fmu'
[Errno 2] No such file or directory: 'examples/simple/resources/Simple2R1C_ic_linux64.fmu'
[Errno 2] No such file or directory: 'examples/simple/resources/Simple2R1C_ic_linux64.fmu'
[Errno 2] No such file or directory: 'examples/simple/resources/Simple2R1C_ic_linux64.fmu'
```

**Comment by robot-army** [comment] 2021-10-12 23:14
OK, so I had to:  

`pip install --upgrade --user pyqtwebengine==5.12`
`pip install --upgrade --user pyqt5==5.12`
` conda update anaconda`
`conda install spyder=5.0.5`
`pip install .\modest-py-master\`

and I was able to run the example, with some fixes to the `os.path.join()` lines to get it pointing at the right directory. 

Let's see how we go...

**Comment by krzysztofarendt** [comment] 2021-10-15 06:50
Hello, I reproduced this issue. When running `examples/simple/simple.py` and other examples I was getting:
```
[Errno 2] No such file or directory: 'examples/simple/resources/Simple2R1C_ic_linux64.fmu'
```

However, it was also followed by another error:
```
OSError: libgfortran.so.3: cannot open shared object file: No such file or directory
```

I'm not sure why it stopped working suddenly (some Ubuntu upgrade?), but this helped:
```
> sudo apt-get install libgfortran3
```

Also, it's better to first clone the repository if you want to run examples, because this way you make sure you have all needed files on disk. `pip install modestpy`  does not download examples. It downloads only the `modestpy` package.

Therefore:
```
> git clone https://github.com/sdu-cfei/modest-py.git
> cd modest-py
> virtualenv -p python3 venv
> source venv/bin/activate
> pip install -e .
> python examples/simple/simple.py
```

Let me know if it helped.

**Comment by krzysztofarendt** [comment] 2021-10-31 09:16
@robot-army , the overflow error means you are multiplying too large numbers (unable to save the result with a given number of bits). If your FMU works fine with the default parameters and fails during the parameter tuning in modestpy, then probably your parameter ranges are too large for this FMU. Try running modestpy with smaller parameter ranges.

I'm closing this issue as it seems the original problem was solved.

**Closed by krzysztofarendt** 2021-10-31 09:16 UTC
Labels: invalid, question
